# Configurations
title:            Home
longtitle:        Home
author:           Benson Hsu
email:            shen485@gmail.com
description: >
  Build Jekyll site with the GitBook style.

version:          1.0
gitbook_version:  3.2.3

url:              'https://Hotshot824.github.io'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: Hotshot824/jekyll-gitbook@mystyle

# Permalinks
permalink: /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts
  - _pages
  - build.sh

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-sitemap
  - jemoji
  - jekyll-remote-theme
